### ISSUE TITLE
Ungültige IK für "St. Martinus Priesterverein VVaG"

### ISSUE THREAD

**Issue by psc161** [PKV-Verband/PKV-IK-Liste#1]
Für "St. Martinus Priesterverein VVaG" ist als IK "12345678" eingetragen.

**Comment by FredNau** [comment]
Hi, das ist nur ein Platzhalter, weil "St. Martinus Priesterverein VVaG" keine IK Nummer hat. Sollten wir einen anderen Platzhalter verwenden?

**Comment by psc161** [comment]
M. E. sollte entweder das Feld leer bleiben, oder die Versicherung erst gar nicht in der Liste auftauchen (wenn man aufgrund fehlender IK eh nichts mit ihr anfangen kann).

**Comment by FredNau** [comment]
Feld ist auskommentiert und Datei aktualisiert
